### PR TITLE
Serialize a `Vec<Enum>` as a map

### PR DESCRIPTION
**Pull request by jonasbb**
Serialize a `Vec` of externally tagged enums to a map with the map key being the external tag.

```rust
vec![
    EnumValue::Int(123),
    EnumValue::String("FooBar".to_string()),
    EnumValue::Int(456),
    EnumValue::String("XXX".to_string()),
    EnumValue::Unit,
    EnumValue::Tuple(1, "Middle".to_string(), false),
    EnumValue::Struct {
        a: 666,
        b: "BBB".to_string(),
        c: true,
    },
],
```

gets converted into this JSON

```json
{
  "Int": 123,
  "String": "FooBar",
  "Int": 456,
  "String": "XXX",
  "Unit": null,
  "Tuple": [
    1,
    "Middle",
    false
  ],
  "Struct": {
    "a": 666,
    "b": "BBB",
    "c": true
  }
}
```

This got requested here: https://github.com/serde-rs/json/issues/743

Todo:
- [x] Update documentation

### CODE REVIEW

**Comment by mathstuf** [comment]
This works for me (in at least one case); I still have another that is not covered here that seems to have some more intricate things. I'm not sure how best to approach this though. If this is a separate request, I'll fine a new issue, but it may be of interest here.

In [this code](https://github.com/mathstuf/rust-bulletml/tree/deserialize-2), the `src/data/data.rs` `EntityRef` is used as an `enum` variant and a `Vec<EntityRef<T>>` struct field. When used as a `struct` field, [this line](https://github.com/mathstuf/rust-bulletml/commit/31221b9e15533960e61420071ce010d63f411de0#diff-72324c0651ad369606d8939db1355f5df2ba792a2da394f8c342f699436e0fffR353) ends up getting called. I can see in the callstack that it goes through `EnumMap::visit_map` and eventually falls onto an `EnumMap::visit_enum` which calls that `todo!()`. Should there be an option to `EnumMap` to pass the key down too (basically just forwarding `visit_map` to the inner visitor)?

**Comment by jonasbb** [comment]
Hi, thanks for taking a look. I think supporting map-like things by handling `deserialize_map` separately and forwarding to the existing `MapAccess` (https://github.com/jonasbb/serde_with/pull/375/commits/19e437befb90bfc00e2bd9bde9fca4eee99dc76e). It does no longer call the `todo!` in your code snippet.

I couldn't test much more, since I don't quite understand how the implementation is supposed to work, especially this part
https://github.com/mathstuf/rust-bulletml/blob/31221b9e15533960e61420071ce010d63f411de0/src/data/data.rs#L375-L381
It deserializes a second key, which must be a `String`, but this deserialization must fail.

**Comment by mathstuf** [comment]
Hrm. That seems to confuse enum types then :/ . I think I'll have to keep peeling back to do custom `Deserialize` impls then see what can be factored out that way.

**Comment by jonasbb** [comment]
@mathstuf Do you have a small-ish example of what you want to deserialize and how the Rust instances should look like?

**Comment by mathstuf** [comment]
That branch now contains code that works with a test suite (the data is in a submodule).

**Comment by jonasbb** [comment]
@mathstuf With a small change, all of your tests pass for me. If you implement `visit_enum` you also need to call `deserialize_enum`. Probably just a leftover from your previous version.

<details>
<summary>Patch</summary>

```diff
diff --git a/src/data/data.rs b/src/data/data.rs
index 90e4bb3..e989c7e 100644
--- a/src/data/data.rs
+++ b/src/data/data.rs
@@ -143,7 +143,7 @@ impl<'de> Deserialize<'de> for Step {
     where
         D: Deserializer<'de>,
     {
-        deserializer.deserialize_map(StepVisitor)
+        deserializer.deserialize_enum("Step", StepVisitor::FIELDS, StepVisitor)
     }
 }
 
@@ -507,7 +507,7 @@ where
     where
         D: Deserializer<'de>,
     {
-        deserializer.deserialize_map(EntityRefVisitor::new())
+        deserializer.deserialize_enum("EntityRef", EntityRefVisitor::<T>::FIELDS, EntityRefVisitor::new())
     }
 }
 ```

 </details>

**Comment by mathstuf** [comment]
Indeed, thanks. I'll keep poking at it down that it works to see if I can remove my custom `impl Deserialize` bits. It might just be too wonky for codegen though.

**Pull request merged**
