### PR TITLE
Add support for chrono::Duration

### PR DESCRIPTION
**Pull request by jonasbb**
Part of #56

### CODE REVIEW

**Comment by Stargateur** [comment]
Some doc would be nice

**Comment by jonasbb** [comment]
I did not manage to document the new code sufficiently, but it is on my agenda. Contributions are welcome too :)

**Comment by jonasbb** [comment]
@Stargateur I added some documentation for `DurationSections` and `DurationSectionsWithFrac` in #153. This is available in master now. I plan on putting out a new preview version soon too.

**Pull request merged**
