### PR TITLE
Generated schemas are not valid when using rust style names in ref

### PR DESCRIPTION
**Pull request by waltronix**
#798

### CODE REVIEW

**Comment by swlynch99** [comment]
I'm not a maintainer of serde-with, just the person who originally wrote the schemars integration. So feel free to ignore this if you want.

With that said, it would be really helpful to document this on the `schema_id` and `schema_name` methods of the `JsonSchemaAs` trait. That the characters need to be valid as a URI path segment for refs to work is very much not apparent unless you are familiar with the json schema spec.

**Comment by jonasbb** [comment]
Hi, thanks for the PR. The change looks fine overall. Adding the extra validation check to the test makes sense.
Do you have a reference which names are allowed? In #798 you listed the three characters `<`, `>`, and `,`. The `,` is still used here and seems to pass the tests.

If the names are invalid anyway, then backwards compatability is not a problem.

**Comment by swlynch99** [comment]
I think it needs to be a URI path segment, so it would be defined in [RFC 3986 section 3.3](https://datatracker.ietf.org/doc/html/rfc3986#section-3.3). That refers back to section 2 and [section 2.2](https://datatracker.ietf.org/doc/html/rfc3986#section-2.2) seems to indicate that all 3 of `(`, `,`, and `)` are valid.

**Comment by waltronix** [comment]
Thanks for your fast response!

I had a mistake in my bug report. There is no problem with the `,` itself, the problem arises from the space after it.

I also extended the doc comment for `schema_name()`. As `schema_id()` is not part of the generated schema according to current documentation I don't think have to require it to be a URI path segment.

**Pull request merged**
